FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_COMPILE_BYTECODE=1 \
    UV_SYSTEM_PYTHON=1

WORKDIR /app

COPY backend_requirements.txt .
RUN uv pip install --no-cache -r backend_requirements.txt

# Backend needs the source code and the main script
COPY src/ ./src/
COPY main.py .

CMD ["uv", "run", "main.py"]