services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    env_file:
      - .env
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    ports:
      - "8050:8050"
    env_file:
      - .env