events {}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80;

    # Serve frontend files
    location / {
      root /frontend;
      index index.html;
      add_header Cache-Control "no-store";
    }

    # Serve data files written by the collector
    location = /latest.json {
      alias /data/latest.json;
      add_header Access-Control-Allow-Origin *;
      add_header Cache-Control "no-cache, no-store";
      add_header Content-Type "application/json";
    }

    location = /prices.parquet {
      alias /data/prices.parquet;
      add_header Access-Control-Allow-Origin *;
      add_header Cache-Control "no-cache";
    }
  }
}
